version: "3.7"

services:
  init:
    container_name: bulgurlumuyum-init
    image: node:15.0-alpine
    volumes:
      - ./app:/app
    networks:
      - net
    command:
      - yarn
      - install

  dev:
    container_name: bulgurlumuyum-dev
    image: bulgurlumuyum:dev
    volumes:
      - ./app:/app
    networks:
      - net
    build:
      context: ./.docker/nodejs/
      target: development-stage
    env_file: .env
    expose:
      - 8080
      - 8000
    ports:
      - 8080:8080
      - 8000:8000
    # command:
    #   - yarn
    #   - serve
    command: /bin/sh -c "while sleep 1000; do :; done"

  build:
    container_name: bulgurlumuyum-build
    image: node:15.0-alpine
    depends_on:
      - init
    volumes:
      - ./app:/app
    networks:
      - net
    command:
      - yarn
      - build

  prod:
    container_name: bulgurlumuyum-prod
    image: nginx:stable-alpine
    depends_on:
      - build
    working_dir: /usr/share/nginx/html
    volumes:
      - ./app/dist:/usr/share/nginx/html:cached
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    env_file: .env
    networks:
      - net
    expose:
      - 80
    ports:
      - 9090:80
    command:
      - nginx
      - -g
      - daemon off;

networks:
  net:
    driver: bridge
