version: "3.7"

services:
  dev:
    container_name: bulgurlumuyum-dev
    image: bulgurlumuyum:dev
    volumes:
      # - node_modules:/app/node_modules
      - ./app:/app
    build:
      context: ./.docker/nodejs/
      target: init-stage
    expose:
      - 8080
    ports:
      - 8080:8080
    command:
      - yarn
      - serve

  build:
    container_name: bulgurlumuyum-build
    image: bulgurlumuyum:build
    build:
      context: ./.docker/nodejs/
      target: init-stage
    volumes:
      - node_modules:/app/node_modules
      - ./app:/app
    command:
      - yarn
      - build

  prod:
    container_name: bulgurlumuyum-prod
    image: nginx:stable-alpine
    depends_on:
      - build
    working_dir: /usr/share/nginx/html
    volumes:
      - ./app/dist:/usr/share/nginx/html
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    expose:
      - 80
    ports:
      - "9090:80"
    command:
      - nginx
      - -g
      - daemon off;

volumes:
  node_modules:
